### ISSUE TITLE
Update Heron version 0.17.2 ?

### ISSUE THREAD

**Issue by thinker0** [streamlio/homebrew-formulae#1]
@aahmed-se

**Comment by aahmed-se** [comment]
will update soon , the formulae structure needs to change since we are publishing different kind of archives now.

**Comment by aahmed-se** [comment]
New unified formulae is published to be used.

**Comment by aahmed-se** [comment]
brew update && brew install streamlio/formulae/heron

**Comment by thinker0** [comment]
LGTM +1
